alter table PROJECT14_REPORT add constraint FK_PROJECT14_REPORT_ON_REPORT_TYPE foreign key (REPORT_TYPE_ID) references PROJECT14_REPORT_TYPE(ID);
create index IDX_PROJECT14_REPORT_ON_REPORT_TYPE on PROJECT14_REPORT (REPORT_TYPE_ID);
